export const flagMap = {
  "ascension island": {
    code: "AC",
    unicode: "U+1F1E6 U+1F1E8",
    name: "Ascension Island",
    emoji: "🇦🇨",
  },
  andorra: {
    code: "AD",
    unicode: "U+1F1E6 U+1F1E9",
    name: "Andorra",
    emoji: "🇦🇩",
  },
  "united arab emirates": {
    code: "AE",
    unicode: "U+1F1E6 U+1F1EA",
    name: "United Arab Emirates",
    emoji: "🇦🇪",
  },
  afghanistan: {
    code: "AF",
    unicode: "U+1F1E6 U+1F1EB",
    name: "Afghanistan",
    emoji: "🇦🇫",
  },
  "antigua & barbuda": {
    code: "AG",
    unicode: "U+1F1E6 U+1F1EC",
    name: "Antigua & Barbuda",
    emoji: "🇦🇬",
  },
  anguilla: {
    code: "AI",
    unicode: "U+1F1E6 U+1F1EE",
    name: "Anguilla",
    emoji: "🇦🇮",
  },
  albania: {
    code: "AL",
    unicode: "U+1F1E6 U+1F1F1",
    name: "Albania",
    emoji: "🇦🇱",
  },
  armenia: {
    code: "AM",
    unicode: "U+1F1E6 U+1F1F2",
    name: "Armenia",
    emoji: "🇦🇲",
  },
  angola: {
    code: "AO",
    unicode: "U+1F1E6 U+1F1F4",
    name: "Angola",
    emoji: "🇦🇴",
  },
  antarctica: {
    code: "AQ",
    unicode: "U+1F1E6 U+1F1F6",
    name: "Antarctica",
    emoji: "🇦🇶",
  },
  argentina: {
    code: "AR",
    unicode: "U+1F1E6 U+1F1F7",
    name: "Argentina",
    emoji: "🇦🇷",
  },
  "american samoa": {
    code: "AS",
    unicode: "U+1F1E6 U+1F1F8",
    name: "American Samoa",
    emoji: "🇦🇸",
  },
  austria: {
    code: "AT",
    unicode: "U+1F1E6 U+1F1F9",
    name: "Austria",
    emoji: "🇦🇹",
  },
  australia: {
    code: "AU",
    unicode: "U+1F1E6 U+1F1FA",
    name: "Australia",
    emoji: "🇦🇺",
  },
  aruba: {
    code: "AW",
    unicode: "U+1F1E6 U+1F1FC",
    name: "Aruba",
    emoji: "🇦🇼",
  },
  "åland islands": {
    code: "AX",
    unicode: "U+1F1E6 U+1F1FD",
    name: "Åland Islands",
    emoji: "🇦🇽",
  },
  azerbaijan: {
    code: "AZ",
    unicode: "U+1F1E6 U+1F1FF",
    name: "Azerbaijan",
    emoji: "🇦🇿",
  },
  "bosnia & herzegovina": {
    code: "BA",
    unicode: "U+1F1E7 U+1F1E6",
    name: "Bosnia & Herzegovina",
    emoji: "🇧🇦",
  },
  barbados: {
    code: "BB",
    unicode: "U+1F1E7 U+1F1E7",
    name: "Barbados",
    emoji: "🇧🇧",
  },
  bangladesh: {
    code: "BD",
    unicode: "U+1F1E7 U+1F1E9",
    name: "Bangladesh",
    emoji: "🇧🇩",
  },
  belgium: {
    code: "BE",
    unicode: "U+1F1E7 U+1F1EA",
    name: "Belgium",
    emoji: "🇧🇪",
  },
  "burkina faso": {
    code: "BF",
    unicode: "U+1F1E7 U+1F1EB",
    name: "Burkina Faso",
    emoji: "🇧🇫",
  },
  bulgaria: {
    code: "BG",
    unicode: "U+1F1E7 U+1F1EC",
    name: "Bulgaria",
    emoji: "🇧🇬",
  },
  bahrain: {
    code: "BH",
    unicode: "U+1F1E7 U+1F1ED",
    name: "Bahrain",
    emoji: "🇧🇭",
  },
  burundi: {
    code: "BI",
    unicode: "U+1F1E7 U+1F1EE",
    name: "Burundi",
    emoji: "🇧🇮",
  },
  benin: {
    code: "BJ",
    unicode: "U+1F1E7 U+1F1EF",
    name: "Benin",
    emoji: "🇧🇯",
  },
  "st. barthélemy": {
    code: "BL",
    unicode: "U+1F1E7 U+1F1F1",
    name: "St. Barthélemy",
    emoji: "🇧🇱",
  },
  bermuda: {
    code: "BM",
    unicode: "U+1F1E7 U+1F1F2",
    name: "Bermuda",
    emoji: "🇧🇲",
  },
  brunei: {
    code: "BN",
    unicode: "U+1F1E7 U+1F1F3",
    name: "Brunei",
    emoji: "🇧🇳",
  },
  bolivia: {
    code: "BO",
    unicode: "U+1F1E7 U+1F1F4",
    name: "Bolivia",
    emoji: "🇧🇴",
  },
  "caribbean netherlands": {
    code: "BQ",
    unicode: "U+1F1E7 U+1F1F6",
    name: "Caribbean Netherlands",
    emoji: "🇧🇶",
  },
  brazil: {
    code: "BR",
    unicode: "U+1F1E7 U+1F1F7",
    name: "Brazil",
    emoji: "🇧🇷",
  },
  bahamas: {
    code: "BS",
    unicode: "U+1F1E7 U+1F1F8",
    name: "Bahamas",
    emoji: "🇧🇸",
  },
  bhutan: {
    code: "BT",
    unicode: "U+1F1E7 U+1F1F9",
    name: "Bhutan",
    emoji: "🇧🇹",
  },
  "bouvet island": {
    code: "BV",
    unicode: "U+1F1E7 U+1F1FB",
    name: "Bouvet Island",
    emoji: "🇧🇻",
  },
  botswana: {
    code: "BW",
    unicode: "U+1F1E7 U+1F1FC",
    name: "Botswana",
    emoji: "🇧🇼",
  },
  belarus: {
    code: "BY",
    unicode: "U+1F1E7 U+1F1FE",
    name: "Belarus",
    emoji: "🇧🇾",
  },
  belize: {
    code: "BZ",
    unicode: "U+1F1E7 U+1F1FF",
    name: "Belize",
    emoji: "🇧🇿",
  },
  canada: {
    code: "CA",
    unicode: "U+1F1E8 U+1F1E6",
    name: "Canada",
    emoji: "🇨🇦",
  },
  "cocos (keeling) islands": {
    code: "CC",
    unicode: "U+1F1E8 U+1F1E8",
    name: "Cocos (Keeling) Islands",
    emoji: "🇨🇨",
  },
  "congo - kinshasa": {
    code: "CD",
    unicode: "U+1F1E8 U+1F1E9",
    name: "Congo - Kinshasa",
    emoji: "🇨🇩",
  },
  "central african republic": {
    code: "CF",
    unicode: "U+1F1E8 U+1F1EB",
    name: "Central African Republic",
    emoji: "🇨🇫",
  },
  "congo - brazzaville": {
    code: "CG",
    unicode: "U+1F1E8 U+1F1EC",
    name: "Congo - Brazzaville",
    emoji: "🇨🇬",
  },
  switzerland: {
    code: "CH",
    unicode: "U+1F1E8 U+1F1ED",
    name: "Switzerland",
    emoji: "🇨🇭",
  },
  "côte d’ivoire": {
    code: "CI",
    unicode: "U+1F1E8 U+1F1EE",
    name: "Côte d’Ivoire",
    emoji: "🇨🇮",
  },
  "cook islands": {
    code: "CK",
    unicode: "U+1F1E8 U+1F1F0",
    name: "Cook Islands",
    emoji: "🇨🇰",
  },
  chile: {
    code: "CL",
    unicode: "U+1F1E8 U+1F1F1",
    name: "Chile",
    emoji: "🇨🇱",
  },
  cameroon: {
    code: "CM",
    unicode: "U+1F1E8 U+1F1F2",
    name: "Cameroon",
    emoji: "🇨🇲",
  },
  china: {
    code: "CN",
    unicode: "U+1F1E8 U+1F1F3",
    name: "China",
    emoji: "🇨🇳",
  },
  colombia: {
    code: "CO",
    unicode: "U+1F1E8 U+1F1F4",
    name: "Colombia",
    emoji: "🇨🇴",
  },
  "clipperton island": {
    code: "CP",
    unicode: "U+1F1E8 U+1F1F5",
    name: "Clipperton Island",
    emoji: "🇨🇵",
  },
  "costa rica": {
    code: "CR",
    unicode: "U+1F1E8 U+1F1F7",
    name: "Costa Rica",
    emoji: "🇨🇷",
  },
  cuba: {
    code: "CU",
    unicode: "U+1F1E8 U+1F1FA",
    name: "Cuba",
    emoji: "🇨🇺",
  },
  "cape verde": {
    code: "CV",
    unicode: "U+1F1E8 U+1F1FB",
    name: "Cape Verde",
    emoji: "🇨🇻",
  },
  curaçao: {
    code: "CW",
    unicode: "U+1F1E8 U+1F1FC",
    name: "Curaçao",
    emoji: "🇨🇼",
  },
  "christmas island": {
    code: "CX",
    unicode: "U+1F1E8 U+1F1FD",
    name: "Christmas Island",
    emoji: "🇨🇽",
  },
  cyprus: {
    code: "CY",
    unicode: "U+1F1E8 U+1F1FE",
    name: "Cyprus",
    emoji: "🇨🇾",
  },
  czechia: {
    code: "CZ",
    unicode: "U+1F1E8 U+1F1FF",
    name: "Czechia",
    emoji: "🇨🇿",
  },
  germany: {
    code: "DE",
    unicode: "U+1F1E9 U+1F1EA",
    name: "Germany",
    emoji: "🇩🇪",
  },
  "diego garcia": {
    code: "DG",
    unicode: "U+1F1E9 U+1F1EC",
    name: "Diego Garcia",
    emoji: "🇩🇬",
  },
  djibouti: {
    code: "DJ",
    unicode: "U+1F1E9 U+1F1EF",
    name: "Djibouti",
    emoji: "🇩🇯",
  },
  denmark: {
    code: "DK",
    unicode: "U+1F1E9 U+1F1F0",
    name: "Denmark",
    emoji: "🇩🇰",
  },
  dominica: {
    code: "DM",
    unicode: "U+1F1E9 U+1F1F2",
    name: "Dominica",
    emoji: "🇩🇲",
  },
  "dominican republic": {
    code: "DO",
    unicode: "U+1F1E9 U+1F1F4",
    name: "Dominican Republic",
    emoji: "🇩🇴",
  },
  algeria: {
    code: "DZ",
    unicode: "U+1F1E9 U+1F1FF",
    name: "Algeria",
    emoji: "🇩🇿",
  },
  "ceuta & melilla": {
    code: "EA",
    unicode: "U+1F1EA U+1F1E6",
    name: "Ceuta & Melilla",
    emoji: "🇪🇦",
  },
  ecuador: {
    code: "EC",
    unicode: "U+1F1EA U+1F1E8",
    name: "Ecuador",
    emoji: "🇪🇨",
  },
  estonia: {
    code: "EE",
    unicode: "U+1F1EA U+1F1EA",
    name: "Estonia",
    emoji: "🇪🇪",
  },
  egypt: {
    code: "EG",
    unicode: "U+1F1EA U+1F1EC",
    name: "Egypt",
    emoji: "🇪🇬",
  },
  "western sahara": {
    code: "EH",
    unicode: "U+1F1EA U+1F1ED",
    name: "Western Sahara",
    emoji: "🇪🇭",
  },
  eritrea: {
    code: "ER",
    unicode: "U+1F1EA U+1F1F7",
    name: "Eritrea",
    emoji: "🇪🇷",
  },
  spain: {
    code: "ES",
    unicode: "U+1F1EA U+1F1F8",
    name: "Spain",
    emoji: "🇪🇸",
  },
  ethiopia: {
    code: "ET",
    unicode: "U+1F1EA U+1F1F9",
    name: "Ethiopia",
    emoji: "🇪🇹",
  },
  "european union": {
    code: "EU",
    unicode: "U+1F1EA U+1F1FA",
    name: "European Union",
    emoji: "🇪🇺",
  },
  finland: {
    code: "FI",
    unicode: "U+1F1EB U+1F1EE",
    name: "Finland",
    emoji: "🇫🇮",
  },
  fiji: {
    code: "FJ",
    unicode: "U+1F1EB U+1F1EF",
    name: "Fiji",
    emoji: "🇫🇯",
  },
  "falkland islands": {
    code: "FK",
    unicode: "U+1F1EB U+1F1F0",
    name: "Falkland Islands",
    emoji: "🇫🇰",
  },
  micronesia: {
    code: "FM",
    unicode: "U+1F1EB U+1F1F2",
    name: "Micronesia",
    emoji: "🇫🇲",
  },
  "faroe islands": {
    code: "FO",
    unicode: "U+1F1EB U+1F1F4",
    name: "Faroe Islands",
    emoji: "🇫🇴",
  },
  france: {
    code: "FR",
    unicode: "U+1F1EB U+1F1F7",
    name: "France",
    emoji: "🇫🇷",
  },
  gabon: {
    code: "GA",
    unicode: "U+1F1EC U+1F1E6",
    name: "Gabon",
    emoji: "🇬🇦",
  },
  "united kingdom": {
    code: "GB",
    unicode: "U+1F1EC U+1F1E7",
    name: "United Kingdom",
    emoji: "🇬🇧",
  },
  grenada: {
    code: "GD",
    unicode: "U+1F1EC U+1F1E9",
    name: "Grenada",
    emoji: "🇬🇩",
  },
  georgia: {
    code: "GE",
    unicode: "U+1F1EC U+1F1EA",
    name: "Georgia",
    emoji: "🇬🇪",
  },
  "french guiana": {
    code: "GF",
    unicode: "U+1F1EC U+1F1EB",
    name: "French Guiana",
    emoji: "🇬🇫",
  },
  guernsey: {
    code: "GG",
    unicode: "U+1F1EC U+1F1EC",
    name: "Guernsey",
    emoji: "🇬🇬",
  },
  ghana: {
    code: "GH",
    unicode: "U+1F1EC U+1F1ED",
    name: "Ghana",
    emoji: "🇬🇭",
  },
  gibraltar: {
    code: "GI",
    unicode: "U+1F1EC U+1F1EE",
    name: "Gibraltar",
    emoji: "🇬🇮",
  },
  greenland: {
    code: "GL",
    unicode: "U+1F1EC U+1F1F1",
    name: "Greenland",
    emoji: "🇬🇱",
  },
  gambia: {
    code: "GM",
    unicode: "U+1F1EC U+1F1F2",
    name: "Gambia",
    emoji: "🇬🇲",
  },
  guinea: {
    code: "GN",
    unicode: "U+1F1EC U+1F1F3",
    name: "Guinea",
    emoji: "🇬🇳",
  },
  guadeloupe: {
    code: "GP",
    unicode: "U+1F1EC U+1F1F5",
    name: "Guadeloupe",
    emoji: "🇬🇵",
  },
  "equatorial guinea": {
    code: "GQ",
    unicode: "U+1F1EC U+1F1F6",
    name: "Equatorial Guinea",
    emoji: "🇬🇶",
  },
  greece: {
    code: "GR",
    unicode: "U+1F1EC U+1F1F7",
    name: "Greece",
    emoji: "🇬🇷",
  },
  "south georgia & south sandwich islands": {
    code: "GS",
    unicode: "U+1F1EC U+1F1F8",
    name: "South Georgia & South Sandwich Islands",
    emoji: "🇬🇸",
  },
  guatemala: {
    code: "GT",
    unicode: "U+1F1EC U+1F1F9",
    name: "Guatemala",
    emoji: "🇬🇹",
  },
  guam: {
    code: "GU",
    unicode: "U+1F1EC U+1F1FA",
    name: "Guam",
    emoji: "🇬🇺",
  },
  "guinea-bissau": {
    code: "GW",
    unicode: "U+1F1EC U+1F1FC",
    name: "Guinea-Bissau",
    emoji: "🇬🇼",
  },
  guyana: {
    code: "GY",
    unicode: "U+1F1EC U+1F1FE",
    name: "Guyana",
    emoji: "🇬🇾",
  },
  "hong kong sar china": {
    code: "HK",
    unicode: "U+1F1ED U+1F1F0",
    name: "Hong Kong SAR China",
    emoji: "🇭🇰",
  },
  "heard & mcdonald islands": {
    code: "HM",
    unicode: "U+1F1ED U+1F1F2",
    name: "Heard & McDonald Islands",
    emoji: "🇭🇲",
  },
  honduras: {
    code: "HN",
    unicode: "U+1F1ED U+1F1F3",
    name: "Honduras",
    emoji: "🇭🇳",
  },
  croatia: {
    code: "HR",
    unicode: "U+1F1ED U+1F1F7",
    name: "Croatia",
    emoji: "🇭🇷",
  },
  haiti: {
    code: "HT",
    unicode: "U+1F1ED U+1F1F9",
    name: "Haiti",
    emoji: "🇭🇹",
  },
  hungary: {
    code: "HU",
    unicode: "U+1F1ED U+1F1FA",
    name: "Hungary",
    emoji: "🇭🇺",
  },
  "canary islands": {
    code: "IC",
    unicode: "U+1F1EE U+1F1E8",
    name: "Canary Islands",
    emoji: "🇮🇨",
  },
  indonesia: {
    code: "ID",
    unicode: "U+1F1EE U+1F1E9",
    name: "Indonesia",
    emoji: "🇮🇩",
  },
  ireland: {
    code: "IE",
    unicode: "U+1F1EE U+1F1EA",
    name: "Ireland",
    emoji: "🇮🇪",
  },
  israel: {
    code: "IL",
    unicode: "U+1F1EE U+1F1F1",
    name: "Israel",
    emoji: "🇮🇱",
  },
  "isle of man": {
    code: "IM",
    unicode: "U+1F1EE U+1F1F2",
    name: "Isle of Man",
    emoji: "🇮🇲",
  },
  india: {
    code: "IN",
    unicode: "U+1F1EE U+1F1F3",
    name: "India",
    emoji: "🇮🇳",
  },
  "british indian ocean territory": {
    code: "IO",
    unicode: "U+1F1EE U+1F1F4",
    name: "British Indian Ocean Territory",
    emoji: "🇮🇴",
  },
  iraq: {
    code: "IQ",
    unicode: "U+1F1EE U+1F1F6",
    name: "Iraq",
    emoji: "🇮🇶",
  },
  iran: {
    code: "IR",
    unicode: "U+1F1EE U+1F1F7",
    name: "Iran",
    emoji: "🇮🇷",
  },
  iceland: {
    code: "IS",
    unicode: "U+1F1EE U+1F1F8",
    name: "Iceland",
    emoji: "🇮🇸",
  },
  italy: {
    code: "IT",
    unicode: "U+1F1EE U+1F1F9",
    name: "Italy",
    emoji: "🇮🇹",
  },
  jersey: {
    code: "JE",
    unicode: "U+1F1EF U+1F1EA",
    name: "Jersey",
    emoji: "🇯🇪",
  },
  jamaica: {
    code: "JM",
    unicode: "U+1F1EF U+1F1F2",
    name: "Jamaica",
    emoji: "🇯🇲",
  },
  jordan: {
    code: "JO",
    unicode: "U+1F1EF U+1F1F4",
    name: "Jordan",
    emoji: "🇯🇴",
  },
  japan: {
    code: "JP",
    unicode: "U+1F1EF U+1F1F5",
    name: "Japan",
    emoji: "🇯🇵",
  },
  kenya: {
    code: "KE",
    unicode: "U+1F1F0 U+1F1EA",
    name: "Kenya",
    emoji: "🇰🇪",
  },
  kyrgyzstan: {
    code: "KG",
    unicode: "U+1F1F0 U+1F1EC",
    name: "Kyrgyzstan",
    emoji: "🇰🇬",
  },
  cambodia: {
    code: "KH",
    unicode: "U+1F1F0 U+1F1ED",
    name: "Cambodia",
    emoji: "🇰🇭",
  },
  kiribati: {
    code: "KI",
    unicode: "U+1F1F0 U+1F1EE",
    name: "Kiribati",
    emoji: "🇰🇮",
  },
  comoros: {
    code: "KM",
    unicode: "U+1F1F0 U+1F1F2",
    name: "Comoros",
    emoji: "🇰🇲",
  },
  "st. kitts & nevis": {
    code: "KN",
    unicode: "U+1F1F0 U+1F1F3",
    name: "St. Kitts & Nevis",
    emoji: "🇰🇳",
  },
  "north korea": {
    code: "KP",
    unicode: "U+1F1F0 U+1F1F5",
    name: "North Korea",
    emoji: "🇰🇵",
  },
  "south korea": {
    code: "KR",
    unicode: "U+1F1F0 U+1F1F7",
    name: "South Korea",
    emoji: "🇰🇷",
  },
  kuwait: {
    code: "KW",
    unicode: "U+1F1F0 U+1F1FC",
    name: "Kuwait",
    emoji: "🇰🇼",
  },
  "cayman islands": {
    code: "KY",
    unicode: "U+1F1F0 U+1F1FE",
    name: "Cayman Islands",
    emoji: "🇰🇾",
  },
  kazakhstan: {
    code: "KZ",
    unicode: "U+1F1F0 U+1F1FF",
    name: "Kazakhstan",
    emoji: "🇰🇿",
  },
  laos: {
    code: "LA",
    unicode: "U+1F1F1 U+1F1E6",
    name: "Laos",
    emoji: "🇱🇦",
  },
  lebanon: {
    code: "LB",
    unicode: "U+1F1F1 U+1F1E7",
    name: "Lebanon",
    emoji: "🇱🇧",
  },
  "st. lucia": {
    code: "LC",
    unicode: "U+1F1F1 U+1F1E8",
    name: "St. Lucia",
    emoji: "🇱🇨",
  },
  liechtenstein: {
    code: "LI",
    unicode: "U+1F1F1 U+1F1EE",
    name: "Liechtenstein",
    emoji: "🇱🇮",
  },
  "sri lanka": {
    code: "LK",
    unicode: "U+1F1F1 U+1F1F0",
    name: "Sri Lanka",
    emoji: "🇱🇰",
  },
  liberia: {
    code: "LR",
    unicode: "U+1F1F1 U+1F1F7",
    name: "Liberia",
    emoji: "🇱🇷",
  },
  lesotho: {
    code: "LS",
    unicode: "U+1F1F1 U+1F1F8",
    name: "Lesotho",
    emoji: "🇱🇸",
  },
  lithuania: {
    code: "LT",
    unicode: "U+1F1F1 U+1F1F9",
    name: "Lithuania",
    emoji: "🇱🇹",
  },
  luxembourg: {
    code: "LU",
    unicode: "U+1F1F1 U+1F1FA",
    name: "Luxembourg",
    emoji: "🇱🇺",
  },
  latvia: {
    code: "LV",
    unicode: "U+1F1F1 U+1F1FB",
    name: "Latvia",
    emoji: "🇱🇻",
  },
  libya: {
    code: "LY",
    unicode: "U+1F1F1 U+1F1FE",
    name: "Libya",
    emoji: "🇱🇾",
  },
  morocco: {
    code: "MA",
    unicode: "U+1F1F2 U+1F1E6",
    name: "Morocco",
    emoji: "🇲🇦",
  },
  monaco: {
    code: "MC",
    unicode: "U+1F1F2 U+1F1E8",
    name: "Monaco",
    emoji: "🇲🇨",
  },
  moldova: {
    code: "MD",
    unicode: "U+1F1F2 U+1F1E9",
    name: "Moldova",
    emoji: "🇲🇩",
  },
  montenegro: {
    code: "ME",
    unicode: "U+1F1F2 U+1F1EA",
    name: "Montenegro",
    emoji: "🇲🇪",
  },
  "st. martin": {
    code: "MF",
    unicode: "U+1F1F2 U+1F1EB",
    name: "St. Martin",
    emoji: "🇲🇫",
  },
  madagascar: {
    code: "MG",
    unicode: "U+1F1F2 U+1F1EC",
    name: "Madagascar",
    emoji: "🇲🇬",
  },
  "marshall islands": {
    code: "MH",
    unicode: "U+1F1F2 U+1F1ED",
    name: "Marshall Islands",
    emoji: "🇲🇭",
  },
  macedonia: {
    code: "MK",
    unicode: "U+1F1F2 U+1F1F0",
    name: "Macedonia",
    emoji: "🇲🇰",
  },
  mali: {
    code: "ML",
    unicode: "U+1F1F2 U+1F1F1",
    name: "Mali",
    emoji: "🇲🇱",
  },
  "myanmar (burma)": {
    code: "MM",
    unicode: "U+1F1F2 U+1F1F2",
    name: "Myanmar (Burma)",
    emoji: "🇲🇲",
  },
  mongolia: {
    code: "MN",
    unicode: "U+1F1F2 U+1F1F3",
    name: "Mongolia",
    emoji: "🇲🇳",
  },
  "macau sar china": {
    code: "MO",
    unicode: "U+1F1F2 U+1F1F4",
    name: "Macau SAR China",
    emoji: "🇲🇴",
  },
  "northern mariana islands": {
    code: "MP",
    unicode: "U+1F1F2 U+1F1F5",
    name: "Northern Mariana Islands",
    emoji: "🇲🇵",
  },
  martinique: {
    code: "MQ",
    unicode: "U+1F1F2 U+1F1F6",
    name: "Martinique",
    emoji: "🇲🇶",
  },
  mauritania: {
    code: "MR",
    unicode: "U+1F1F2 U+1F1F7",
    name: "Mauritania",
    emoji: "🇲🇷",
  },
  montserrat: {
    code: "MS",
    unicode: "U+1F1F2 U+1F1F8",
    name: "Montserrat",
    emoji: "🇲🇸",
  },
  malta: {
    code: "MT",
    unicode: "U+1F1F2 U+1F1F9",
    name: "Malta",
    emoji: "🇲🇹",
  },
  mauritius: {
    code: "MU",
    unicode: "U+1F1F2 U+1F1FA",
    name: "Mauritius",
    emoji: "🇲🇺",
  },
  maldives: {
    code: "MV",
    unicode: "U+1F1F2 U+1F1FB",
    name: "Maldives",
    emoji: "🇲🇻",
  },
  malawi: {
    code: "MW",
    unicode: "U+1F1F2 U+1F1FC",
    name: "Malawi",
    emoji: "🇲🇼",
  },
  mexico: {
    code: "MX",
    unicode: "U+1F1F2 U+1F1FD",
    name: "Mexico",
    emoji: "🇲🇽",
  },
  malaysia: {
    code: "MY",
    unicode: "U+1F1F2 U+1F1FE",
    name: "Malaysia",
    emoji: "🇲🇾",
  },
  mozambique: {
    code: "MZ",
    unicode: "U+1F1F2 U+1F1FF",
    name: "Mozambique",
    emoji: "🇲🇿",
  },
  namibia: {
    code: "NA",
    unicode: "U+1F1F3 U+1F1E6",
    name: "Namibia",
    emoji: "🇳🇦",
  },
  "new caledonia": {
    code: "NC",
    unicode: "U+1F1F3 U+1F1E8",
    name: "New Caledonia",
    emoji: "🇳🇨",
  },
  niger: {
    code: "NE",
    unicode: "U+1F1F3 U+1F1EA",
    name: "Niger",
    emoji: "🇳🇪",
  },
  "norfolk island": {
    code: "NF",
    unicode: "U+1F1F3 U+1F1EB",
    name: "Norfolk Island",
    emoji: "🇳🇫",
  },
  nigeria: {
    code: "NG",
    unicode: "U+1F1F3 U+1F1EC",
    name: "Nigeria",
    emoji: "🇳🇬",
  },
  nicaragua: {
    code: "NI",
    unicode: "U+1F1F3 U+1F1EE",
    name: "Nicaragua",
    emoji: "🇳🇮",
  },
  netherlands: {
    code: "NL",
    unicode: "U+1F1F3 U+1F1F1",
    name: "Netherlands",
    emoji: "🇳🇱",
  },
  norway: {
    code: "NO",
    unicode: "U+1F1F3 U+1F1F4",
    name: "Norway",
    emoji: "🇳🇴",
  },
  nepal: {
    code: "NP",
    unicode: "U+1F1F3 U+1F1F5",
    name: "Nepal",
    emoji: "🇳🇵",
  },
  nauru: {
    code: "NR",
    unicode: "U+1F1F3 U+1F1F7",
    name: "Nauru",
    emoji: "🇳🇷",
  },
  niue: {
    code: "NU",
    unicode: "U+1F1F3 U+1F1FA",
    name: "Niue",
    emoji: "🇳🇺",
  },
  "new zealand": {
    code: "NZ",
    unicode: "U+1F1F3 U+1F1FF",
    name: "New Zealand",
    emoji: "🇳🇿",
  },
  oman: {
    code: "OM",
    unicode: "U+1F1F4 U+1F1F2",
    name: "Oman",
    emoji: "🇴🇲",
  },
  panama: {
    code: "PA",
    unicode: "U+1F1F5 U+1F1E6",
    name: "Panama",
    emoji: "🇵🇦",
  },
  peru: {
    code: "PE",
    unicode: "U+1F1F5 U+1F1EA",
    name: "Peru",
    emoji: "🇵🇪",
  },
  "french polynesia": {
    code: "PF",
    unicode: "U+1F1F5 U+1F1EB",
    name: "French Polynesia",
    emoji: "🇵🇫",
  },
  "papua new guinea": {
    code: "PG",
    unicode: "U+1F1F5 U+1F1EC",
    name: "Papua New Guinea",
    emoji: "🇵🇬",
  },
  philippines: {
    code: "PH",
    unicode: "U+1F1F5 U+1F1ED",
    name: "Philippines",
    emoji: "🇵🇭",
  },
  pakistan: {
    code: "PK",
    unicode: "U+1F1F5 U+1F1F0",
    name: "Pakistan",
    emoji: "🇵🇰",
  },
  poland: {
    code: "PL",
    unicode: "U+1F1F5 U+1F1F1",
    name: "Poland",
    emoji: "🇵🇱",
  },
  "st. pierre & miquelon": {
    code: "PM",
    unicode: "U+1F1F5 U+1F1F2",
    name: "St. Pierre & Miquelon",
    emoji: "🇵🇲",
  },
  "pitcairn islands": {
    code: "PN",
    unicode: "U+1F1F5 U+1F1F3",
    name: "Pitcairn Islands",
    emoji: "🇵🇳",
  },
  "puerto rico": {
    code: "PR",
    unicode: "U+1F1F5 U+1F1F7",
    name: "Puerto Rico",
    emoji: "🇵🇷",
  },
  "palestinian territories": {
    code: "PS",
    unicode: "U+1F1F5 U+1F1F8",
    name: "Palestinian Territories",
    emoji: "🇵🇸",
  },
  portugal: {
    code: "PT",
    unicode: "U+1F1F5 U+1F1F9",
    name: "Portugal",
    emoji: "🇵🇹",
  },
  palau: {
    code: "PW",
    unicode: "U+1F1F5 U+1F1FC",
    name: "Palau",
    emoji: "🇵🇼",
  },
  paraguay: {
    code: "PY",
    unicode: "U+1F1F5 U+1F1FE",
    name: "Paraguay",
    emoji: "🇵🇾",
  },
  qatar: {
    code: "QA",
    unicode: "U+1F1F6 U+1F1E6",
    name: "Qatar",
    emoji: "🇶🇦",
  },
  réunion: {
    code: "RE",
    unicode: "U+1F1F7 U+1F1EA",
    name: "Réunion",
    emoji: "🇷🇪",
  },
  romania: {
    code: "RO",
    unicode: "U+1F1F7 U+1F1F4",
    name: "Romania",
    emoji: "🇷🇴",
  },
  serbia: {
    code: "RS",
    unicode: "U+1F1F7 U+1F1F8",
    name: "Serbia",
    emoji: "🇷🇸",
  },
  russia: {
    code: "RU",
    unicode: "U+1F1F7 U+1F1FA",
    name: "Russia",
    emoji: "🇷🇺",
  },
  rwanda: {
    code: "RW",
    unicode: "U+1F1F7 U+1F1FC",
    name: "Rwanda",
    emoji: "🇷🇼",
  },
  "saudi arabia": {
    code: "SA",
    unicode: "U+1F1F8 U+1F1E6",
    name: "Saudi Arabia",
    emoji: "🇸🇦",
  },
  "solomon islands": {
    code: "SB",
    unicode: "U+1F1F8 U+1F1E7",
    name: "Solomon Islands",
    emoji: "🇸🇧",
  },
  seychelles: {
    code: "SC",
    unicode: "U+1F1F8 U+1F1E8",
    name: "Seychelles",
    emoji: "🇸🇨",
  },
  sudan: {
    code: "SD",
    unicode: "U+1F1F8 U+1F1E9",
    name: "Sudan",
    emoji: "🇸🇩",
  },
  sweden: {
    code: "SE",
    unicode: "U+1F1F8 U+1F1EA",
    name: "Sweden",
    emoji: "🇸🇪",
  },
  singapore: {
    code: "SG",
    unicode: "U+1F1F8 U+1F1EC",
    name: "Singapore",
    emoji: "🇸🇬",
  },
  "st. helena": {
    code: "SH",
    unicode: "U+1F1F8 U+1F1ED",
    name: "St. Helena",
    emoji: "🇸🇭",
  },
  slovenia: {
    code: "SI",
    unicode: "U+1F1F8 U+1F1EE",
    name: "Slovenia",
    emoji: "🇸🇮",
  },
  "svalbard & jan mayen": {
    code: "SJ",
    unicode: "U+1F1F8 U+1F1EF",
    name: "Svalbard & Jan Mayen",
    emoji: "🇸🇯",
  },
  slovakia: {
    code: "SK",
    unicode: "U+1F1F8 U+1F1F0",
    name: "Slovakia",
    emoji: "🇸🇰",
  },
  "sierra leone": {
    code: "SL",
    unicode: "U+1F1F8 U+1F1F1",
    name: "Sierra Leone",
    emoji: "🇸🇱",
  },
  "san marino": {
    code: "SM",
    unicode: "U+1F1F8 U+1F1F2",
    name: "San Marino",
    emoji: "🇸🇲",
  },
  senegal: {
    code: "SN",
    unicode: "U+1F1F8 U+1F1F3",
    name: "Senegal",
    emoji: "🇸🇳",
  },
  somalia: {
    code: "SO",
    unicode: "U+1F1F8 U+1F1F4",
    name: "Somalia",
    emoji: "🇸🇴",
  },
  suriname: {
    code: "SR",
    unicode: "U+1F1F8 U+1F1F7",
    name: "Suriname",
    emoji: "🇸🇷",
  },
  "south sudan": {
    code: "SS",
    unicode: "U+1F1F8 U+1F1F8",
    name: "South Sudan",
    emoji: "🇸🇸",
  },
  "são tomé & príncipe": {
    code: "ST",
    unicode: "U+1F1F8 U+1F1F9",
    name: "São Tomé & Príncipe",
    emoji: "🇸🇹",
  },
  "el salvador": {
    code: "SV",
    unicode: "U+1F1F8 U+1F1FB",
    name: "El Salvador",
    emoji: "🇸🇻",
  },
  "sint maarten": {
    code: "SX",
    unicode: "U+1F1F8 U+1F1FD",
    name: "Sint Maarten",
    emoji: "🇸🇽",
  },
  syria: {
    code: "SY",
    unicode: "U+1F1F8 U+1F1FE",
    name: "Syria",
    emoji: "🇸🇾",
  },
  swaziland: {
    code: "SZ",
    unicode: "U+1F1F8 U+1F1FF",
    name: "Swaziland",
    emoji: "🇸🇿",
  },
  "tristan da cunha": {
    code: "TA",
    unicode: "U+1F1F9 U+1F1E6",
    name: "Tristan da Cunha",
    emoji: "🇹🇦",
  },
  "turks & caicos islands": {
    code: "TC",
    unicode: "U+1F1F9 U+1F1E8",
    name: "Turks & Caicos Islands",
    emoji: "🇹🇨",
  },
  chad: {
    code: "TD",
    unicode: "U+1F1F9 U+1F1E9",
    name: "Chad",
    emoji: "🇹🇩",
  },
  "french southern territories": {
    code: "TF",
    unicode: "U+1F1F9 U+1F1EB",
    name: "French Southern Territories",
    emoji: "🇹🇫",
  },
  togo: {
    code: "TG",
    unicode: "U+1F1F9 U+1F1EC",
    name: "Togo",
    emoji: "🇹🇬",
  },
  thailand: {
    code: "TH",
    unicode: "U+1F1F9 U+1F1ED",
    name: "Thailand",
    emoji: "🇹🇭",
  },
  tajikistan: {
    code: "TJ",
    unicode: "U+1F1F9 U+1F1EF",
    name: "Tajikistan",
    emoji: "🇹🇯",
  },
  tokelau: {
    code: "TK",
    unicode: "U+1F1F9 U+1F1F0",
    name: "Tokelau",
    emoji: "🇹🇰",
  },
  "timor-leste": {
    code: "TL",
    unicode: "U+1F1F9 U+1F1F1",
    name: "Timor-Leste",
    emoji: "🇹🇱",
  },
  turkmenistan: {
    code: "TM",
    unicode: "U+1F1F9 U+1F1F2",
    name: "Turkmenistan",
    emoji: "🇹🇲",
  },
  tunisia: {
    code: "TN",
    unicode: "U+1F1F9 U+1F1F3",
    name: "Tunisia",
    emoji: "🇹🇳",
  },
  tonga: {
    code: "TO",
    unicode: "U+1F1F9 U+1F1F4",
    name: "Tonga",
    emoji: "🇹🇴",
  },
  turkey: {
    code: "TR",
    unicode: "U+1F1F9 U+1F1F7",
    name: "Turkey",
    emoji: "🇹🇷",
  },
  "trinidad & tobago": {
    code: "TT",
    unicode: "U+1F1F9 U+1F1F9",
    name: "Trinidad & Tobago",
    emoji: "🇹🇹",
  },
  tuvalu: {
    code: "TV",
    unicode: "U+1F1F9 U+1F1FB",
    name: "Tuvalu",
    emoji: "🇹🇻",
  },
  taiwan: {
    code: "TW",
    unicode: "U+1F1F9 U+1F1FC",
    name: "Taiwan",
    emoji: "🇹🇼",
  },
  tanzania: {
    code: "TZ",
    unicode: "U+1F1F9 U+1F1FF",
    name: "Tanzania",
    emoji: "🇹🇿",
  },
  ukraine: {
    code: "UA",
    unicode: "U+1F1FA U+1F1E6",
    name: "Ukraine",
    emoji: "🇺🇦",
  },
  uganda: {
    code: "UG",
    unicode: "U+1F1FA U+1F1EC",
    name: "Uganda",
    emoji: "🇺🇬",
  },
  "u.s. outlying islands": {
    code: "UM",
    unicode: "U+1F1FA U+1F1F2",
    name: "U.S. Outlying Islands",
    emoji: "🇺🇲",
  },
  "united nations": {
    code: "UN",
    unicode: "U+1F1FA U+1F1F3",
    name: "United Nations",
    emoji: "🇺🇳",
  },
  "united states of america": {
    code: "US",
    unicode: "U+1F1FA U+1F1F8",
    name: "United States",
    emoji: "🇺🇸",
  },
  uruguay: {
    code: "UY",
    unicode: "U+1F1FA U+1F1FE",
    name: "Uruguay",
    emoji: "🇺🇾",
  },
  uzbekistan: {
    code: "UZ",
    unicode: "U+1F1FA U+1F1FF",
    name: "Uzbekistan",
    emoji: "🇺🇿",
  },
  "vatican city": {
    code: "VA",
    unicode: "U+1F1FB U+1F1E6",
    name: "Vatican City",
    emoji: "🇻🇦",
  },
  "st. vincent & grenadines": {
    code: "VC",
    unicode: "U+1F1FB U+1F1E8",
    name: "St. Vincent & Grenadines",
    emoji: "🇻🇨",
  },
  venezuela: {
    code: "VE",
    unicode: "U+1F1FB U+1F1EA",
    name: "Venezuela",
    emoji: "🇻🇪",
  },
  "british virgin islands": {
    code: "VG",
    unicode: "U+1F1FB U+1F1EC",
    name: "British Virgin Islands",
    emoji: "🇻🇬",
  },
  "u.s. virgin islands": {
    code: "VI",
    unicode: "U+1F1FB U+1F1EE",
    name: "U.S. Virgin Islands",
    emoji: "🇻🇮",
  },
  vietnam: {
    code: "VN",
    unicode: "U+1F1FB U+1F1F3",
    name: "Vietnam",
    emoji: "🇻🇳",
  },
  vanuatu: {
    code: "VU",
    unicode: "U+1F1FB U+1F1FA",
    name: "Vanuatu",
    emoji: "🇻🇺",
  },
  "wallis & futuna": {
    code: "WF",
    unicode: "U+1F1FC U+1F1EB",
    name: "Wallis & Futuna",
    emoji: "🇼🇫",
  },
  samoa: {
    code: "WS",
    unicode: "U+1F1FC U+1F1F8",
    name: "Samoa",
    emoji: "🇼🇸",
  },
  kosovo: {
    code: "XK",
    unicode: "U+1F1FD U+1F1F0",
    name: "Kosovo",
    emoji: "🇽🇰",
  },
  yemen: {
    code: "YE",
    unicode: "U+1F1FE U+1F1EA",
    name: "Yemen",
    emoji: "🇾🇪",
  },
  mayotte: {
    code: "YT",
    unicode: "U+1F1FE U+1F1F9",
    name: "Mayotte",
    emoji: "🇾🇹",
  },
  "south africa": {
    code: "ZA",
    unicode: "U+1F1FF U+1F1E6",
    name: "South Africa",
    emoji: "🇿🇦",
  },
  zambia: {
    code: "ZM",
    unicode: "U+1F1FF U+1F1F2",
    name: "Zambia",
    emoji: "🇿🇲",
  },
  zimbabwe: {
    code: "ZW",
    unicode: "U+1F1FF U+1F1FC",
    name: "Zimbabwe",
    emoji: "🇿🇼",
  },
}
// Function to convert Unicode string like "U+1F1FF U+1F1FC" to actual emoji
const convertUnicodeToEmoji = (unicodeString: string): string => {
  if (!unicodeString) return ""

  // Split by spaces and convert each Unicode code point
  const codePoints = unicodeString.split(" ")
  let emoji = ""

  for (const codePoint of codePoints) {
    if (codePoint.startsWith("U+")) {
      // Remove "U+" prefix and convert hex to decimal
      const hex = codePoint.substring(2)
      const decimal = parseInt(hex, 16)
      emoji += String.fromCodePoint(decimal)
    }
  }

  return emoji
}

export const getFlagEmojiByCountryName = (countryName: string) => {
  const countryData = flagMap[countryName.toLowerCase() as keyof typeof flagMap]
  if (!countryData) return ""

  // Convert Unicode string to actual emoji
  return convertUnicodeToEmoji(countryData.unicode)
}
