name: lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    env:
      STAGE_SSV_NETWORKS: >
        [
          {
            "networkId": 560048,
            "apiVersion": "v4",
            "apiNetwork": "hoodi",
            "api": "https://api.stage.ops.ssvlabsinternal.com/api",
            "explorerUrl": "https://hoodi-explorer.stage.ssv.network",
            "insufficientBalanceUrl": "https://faucet.stage.ssv.network",
            "tokenAddress": "0x746c33ccc28b1363c35c09badaf41b2ffa7e6d56",
            "setterContractAddress": "0xc07B3E9671f884FDa67E1e7D43d952E0e1369fd8",
            "getterContractAddress": "0x3234e84b7d1eE1AF8b586E26814d4e268336D142"
          }
        ]
      MAIN_PREVIEW_SSV_NETWORKS: >
        [
          {
            "networkId": 560048,
            "apiVersion": "v4",
            "apiNetwork": "hoodi",
            "api": "https://api.hoodi.ssv.network/api",
            "explorerUrl": "https://hoodi.etherscan.io",
            "insufficientBalanceUrl": "https://faucet.ssv.network/",
            "tokenAddress": "0x9F5d4Ec84fC4785788aB44F9de973cF34F7A038e",
            "setterContractAddress": "0x58410Bef803ECd7E63B23664C586A6DB72DAf59c",
            "getterContractAddress": "0x5AdDb3f1529C5ec70D77400499eE4bbF328368fe"
          },
          {
            "networkId": 1,
            "apiVersion": "v4",
            "apiNetwork": "mainnet",
            "api": "https://api.ssv.network/api",
            "explorerUrl": "https://etherscan.io",
            "insufficientBalanceUrl": "https://faucet.ssv.network/",
            "tokenAddress": "0x9D65fF81a3c488d585bBfb0Bfe3c7707c7917f54",
            "setterContractAddress": "0xDD9BC35aE942eF0cFa76930954a156B3fF30a4E1",
            "getterContractAddress": "0xafE830B6Ee262ba11cce5F32fDCd760FFE6a66e4"
          }
        ]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 20.19.6

      - uses: pnpm/action-setup@v2
        with:
          version: 10.20.0

      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm typegen && pnpm lint
        env:
          SKIP_ENV_VALIDATION: true

      - name: Run test stage build
        if: github.ref == 'refs/heads/stage'
        env:
          SSV_NETWORKS: "${{ env.STAGE_SSV_NETWORKS }}"
          NEXT_PUBLIC_SSV_NETWORKS: "${{ env.STAGE_SSV_NETWORKS }}"
          SITE_URL: "https://explorer.stage.ssv.network"
          NEXT_PUBLIC_COINGECKO_API_URL: "https://api.coingecko.com/api/"

        run: pnpm build

      - name: Run test main-preview build
        if: github.ref == 'refs/heads/main-preview'
        env:
          SSV_NETWORKS: "${{ env.MAIN_PREVIEW_SSV_NETWORKS }}"
          NEXT_PUBLIC_SSV_NETWORKS: "${{ env.MAIN_PREVIEW_SSV_NETWORKS }}"
          SITE_URL: "https://explorer.ssv.network"
          NEXT_PUBLIC_COINGECKO_API_URL: "https://api.coingecko.com/api/"

        run: pnpm build
