name: lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    env:
      STAGE_SSV_NETWORKS: >
        [
          {
            "networkId": 560048,
            "apiVersion": "v4",
            "apiNetwork": "hoodi",
            "api": "https://api.stage.ops.ssvlabsinternal.com/api",
            "explorerUrl": "https://hoodi-explorer.stage.ssv.network",
            "insufficientBalanceUrl": "https://faucet.stage.ssv.network",
            "googleTagSecret": "87987987987",
            "tokenAddress": "0x746c33ccc28b1363c35c09badaf41b2ffa7e6d56",
            "bAppContractAddress": "0x40d959B95e7c56962D6d388d87921c03734b9C2C",
            "setterContractAddress": "0xc07B3E9671f884FDa67E1e7D43d952E0e1369fd8",
            "getterContractAddress": "0x3234e84b7d1eE1AF8b586E26814d4e268336D142"
          }
        ]

    steps:
      - uses: actions/checkout@v6.0.2 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6.3.0 # v3
        with:
          node-version: 20.19.6

      - uses: pnpm/action-setup@v5.0.0
        with:
          version: 10.20.0

      - uses: actions/cache@v5.0.4 # v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm typegen && pnpm lint
        env:
          SKIP_ENV_VALIDATION: true

      - name: Run test stage build
        if: github.ref == 'refs/heads/stage'
        env:
          SSV_NETWORKS: "${{ env.STAGE_SSV_NETWORKS }}"
          NEXT_PUBLIC_SSV_NETWORKS: "${{ env.STAGE_SSV_NETWORKS }}"
          SITE_URL: "https://explorer.stage.ssv.network"

        run: pnpm build
